services:
  - type: web
    name: healthtrackermichele
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build && cd .. && \
      pip install -r requirements.txt && \
      mkdir -p backend/static/dist && \
      cp -r frontend/dist/* backend/static/dist/
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
