"""Initial migration

Revision ID: bd64caab1b9b
Revises: 
Create Date: 2025-02-26 00:06:01.065542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd64caab1b9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_health_data_data_type'), 'health_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_health_data_timestamp'), 'health_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_data_user_id'), 'health_data', ['user_id'], unique=False)
    op.create_index('ix_health_data_user_type_time', 'health_data', ['user_id', 'data_type', 'timestamp'], unique=False)
    op.drop_constraint('health_data_user_id_fkey', 'health_data', type_='foreignkey')
    op.create_foreign_key(None, 'health_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('reports', sa.Column('care_recommendation', sa.Enum('HOME_CARE', 'SEE_DOCTOR', 'URGENT_CARE', name='care_recommendation_enum'), nullable=True))
    op.create_index(op.f('ix_reports_care_recommendation'), 'reports', ['care_recommendation'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.create_index('ix_reports_title_text', 'reports', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('revoked_tokens_jti_key', 'revoked_tokens', type_='unique')
    op.create_index(op.f('ix_revoked_tokens_created_at'), 'revoked_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.add_column('symptom_logs', sa.Column('symptom_name', sa.String(length=100), nullable=True))
    op.alter_column('symptom_logs', 'symptom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_symptom_logs_severity'), 'symptom_logs', ['severity'], unique=False)
    op.create_index('ix_symptom_logs_severity_timestamp', 'symptom_logs', ['severity', 'timestamp'], unique=False)
    op.create_index(op.f('ix_symptom_logs_symptom_id'), 'symptom_logs', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_symptom_name'), 'symptom_logs', ['symptom_name'], unique=False)
    op.create_index(op.f('ix_symptom_logs_timestamp'), 'symptom_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.create_index('ix_symptom_logs_user_timestamp', 'symptom_logs', ['user_id', 'timestamp'], unique=False)
    op.drop_constraint('symptom_logs_symptom_id_fkey', 'symptom_logs', type_='foreignkey')
    op.drop_constraint('symptom_logs_user_id_fkey', 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'symptom_logs', 'symptoms', ['symptom_id'], ['id'], ondelete='SET NULL')
    op.add_column('symptoms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_symptoms_deleted_at'), 'symptoms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=False)
    op.create_index('ix_symptoms_name_text', 'symptoms', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_users_username_subscription', 'users', ['username', 'subscription_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_subscription', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'subscription_tier')
    op.drop_index('ix_symptoms_name_text', table_name='symptoms', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_deleted_at'), table_name='symptoms')
    op.drop_column('symptoms', 'deleted_at')
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.create_foreign_key('symptom_logs_user_id_fkey', 'symptom_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('symptom_logs_symptom_id_fkey', 'symptom_logs', 'symptoms', ['symptom_id'], ['id'])
    op.drop_index('ix_symptom_logs_user_timestamp', table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_timestamp'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_symptom_name'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_symptom_id'), table_name='symptom_logs')
    op.drop_index('ix_symptom_logs_severity_timestamp', table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_severity'), table_name='symptom_logs')
    op.alter_column('symptom_logs', 'symptom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('symptom_logs', 'symptom_name')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_created_at'), table_name='revoked_tokens')
    op.create_unique_constraint('revoked_tokens_jti_key', 'revoked_tokens', ['jti'])
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index('ix_reports_user_created', table_name='reports')
    op.drop_index('ix_reports_title_text', table_name='reports', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_care_recommendation'), table_name='reports')
    op.drop_column('reports', 'care_recommendation')
    op.drop_constraint(None, 'health_data', type_='foreignkey')
    op.create_foreign_key('health_data_user_id_fkey', 'health_data', 'users', ['user_id'], ['id'])
    op.drop_index('ix_health_data_user_type_time', table_name='health_data')
    op.drop_index(op.f('ix_health_data_user_id'), table_name='health_data')
    op.drop_index(op.f('ix_health_data_timestamp'), table_name='health_data')
    op.drop_index(op.f('ix_health_data_data_type'), table_name='health_data')
    # ### end Alembic commands ###
